camunda.bpm:
  database:
    type: postgres
  table-prefix: camunda.
  schema-update: true
  admin-user:
    id: demo
    password: demo

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: "@D3lt44pp1234*"
  main:
    allow-bean-definition-overriding: true